<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AccesoSeguroPAC" targetNamespace="http://servicios.wspac.crm.sds.telcel.com.mx/" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="http://servicios.wspac.crm.sds.telcel.com.mx/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://servicios.wspac.crm.sds.telcel.com.mx/" schemaLocation="AccesoSeguroPAC_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="validaTokenResponse">
    <part name="parameters" element="tns:validaTokenResponse">
    </part>
  </message>
  <message name="validaToken">
    <part name="parameters" element="tns:validaToken">
    </part>
  </message>
  <message name="Exception">
    <part name="fault" element="tns:Exception">
    </part>
  </message>
  <portType name="AccesoSeguroPAC">
    <operation name="validaToken">
      <input message="tns:validaToken" wsam:Action="http://servicios.wspac.crm.sds.telcel.com.mx/AccesoSeguroPAC/validaTokenRequest">
    </input>
      <output message="tns:validaTokenResponse" wsam:Action="http://servicios.wspac.crm.sds.telcel.com.mx/AccesoSeguroPAC/validaTokenResponse">
    </output>
      <fault name="Exception" message="tns:Exception" wsam:Action="http://servicios.wspac.crm.sds.telcel.com.mx/AccesoSeguroPAC/validaToken/Fault/Exception">
    </fault>
    </operation>
  </portType>
  <binding name="AccesoSeguroPACPortBinding" type="tns:AccesoSeguroPAC">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="validaToken">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="Exception">
        <soap:fault name="Exception" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="AccesoSeguroPAC">
    <port name="AccesoSeguroPACPort" binding="tns:AccesoSeguroPACPortBinding">
      <soap:address location="http://pac.telcel.com:9086/PACServiciosWeb/AccesoSeguroPAC"/>
    </port>
  </service>
</definitions>